### ISSUE TITLE
`schema inspect` with MySQL Unix socket uses socket path as the schema name

### ISSUE THREAD

**Issue by ariel-co** [ariga/atlas#2472]
I'm trying to connect via Unix socket while specifying the password. This works with the command line client:

```
$ mysql -s -u root -S /san/mysql-fs/mysql/mysql.sock -p
Enter password:
mysql>

```

With Atlas, putting the password (after urlencoding a '=' in the middle) in the URL, this is what I get:
```

$ ./atlas schema inspect -u "mysql+unix://root:mysikrit%3Dpasswd@/san/mysql-fs/mysql/mysql.sock?database=mydatabase" > mydatabase.hcl
Error: mysql: schema "san/mysql-fs/mysql/mysql.sock" was not found

```

Notice how it strips the first `/` from the socket path and takes that as the schema name. Removing `?database=mydatabase` has no effect.

    $ ./atlas version
    atlas version v0.18.1-60783c4-canary

**Comment by xaverhimmelsbach** [comment]
This is broken for us as well. It should have been fixed in https://github.com/ariga/atlas/issues/1587 but looking at the tests in https://github.com/ariga/atlas/blob/master/sql/mysql/driver_test.go for ParseURL, everything seems to work fine.

Maybe the leading slash gets stripped and the schema is extracted in an earlier, step. Sadly, I don't know the code well enough to find any place like that. @a8m do you have any input on this?

**Comment by c24-jens-albert** [comment]
We encountered the same problem, but not only with `schema`, but also with `migrate`:
```
atlas migrate apply --dir file://db/migration --url "mysql+unix://user:$DB_PW@/run/proxysql/proxysql.sock?database=dbname"

Error: add new schema named "run/proxysql/proxysql.sock": Error 1044 (42000): Access denied for user 'user'@'10.10.10.100' to database 'run/proxysql/proxysql.sock'

```
But according to the [Docs](https://atlasgo.io/concepts/url) and #1587 it should work? Is this a known problem?

**Comment by a8m** [comment]
<img width="537" alt="image" src="https://github.com/ariga/atlas/assets/7413593/12ce88eb-3eaf-4b5b-9b74-91e357becffd">

This won't make me support you faster, sorry.

**Comment by a8m** [comment]
@ariel-co, I just tested it locally and it seems to work without any issues. You can try upgrading your Atlas version (download  it and don't compile from source) and report if you face any issues with it. 

@xaverhimmelsbach, @c24-jens-albert - escape the password and pass it to Atlas. That's probably your issue.

**Comment by ttc0419** [comment]
@a8m Hi, seems the problem is not fixed, could you please take a look at it again? I'm using the version installed from homebrew on macOS.
```
[u@h d]% atlas schema inspect -u 'mysql+unix://test:test@/tmp/mysql.sock?database=test'
Error: mysql: schema "tmp/mysql.sock" was not found

[u@h d]% file /tmp/mysql.sock
/tmp/mysql.sock: socket

[u@h d]% atlas version
atlas unofficial version v0.23.0
https://github.com/ariga/atlas/releases/tag/v0.23.0
To download an official version, visit: https://atlasgo.io/getting-started#installation
```
