### ISSUE TITLE
Bypass interactive approval for column `RENAME` detection

### ISSUE THREAD

**Issue by acaruso7** [ariga/atlas#2956]
I'm getting stuck on the interactive approval for column RENAME detection for an `atlas schema apply . . . --auto-approve` invocation in a automated deployment context

I see this feature was added in v 0.22 - https://atlasgo.io/blog/2024/05/01/atlas-v-0-22#rename-detection

When atlas detects a column rename, it interactively opens the following prompt:

```
? Did you rename "<table>" column from "<old>" to "<new>": 
  ▸ Yes
    No
```

I figured that the `--auto-approve` flag would bypass this, but apparently not

Is there any way to bypass this and automatically apply detected column renames?

**Comment by rotemtam** [comment]
Hi @acaruso7,

Thanks for reaching out. We just pushed a fix that should resolve this for situations where the user isn't connected to a TTY. 

Can you try again with the most recent version of Atlas? 

```
curl -sSf https://atlasgo.sh | sh
```

**Comment by acaruso7** [comment]
Hi @rotemtam I just tried again on version `v0.25.1-965bcf5-canary` (installed from above command), but it's still interactively asking for approval

My atlas command:

```
atlas schema apply --url 'postgresql://postgres:admin@db/app?search_path=app&sslmode=disable' --to 'file://schema.sql' --dev-url 'postgresql://postgres:admin@db/atlas?search_path=app&sslmode=disable' --auto-approve
```

**Comment by rotemtam** [comment]
The fix was for non interactive environments, such as CI pipelines. Do you get that there as well?

**Comment by acaruso7** [comment]
Yes still getting stuck on the same in a CI environment (GitHub Actions invoking kubernetes migration job runners)

**Comment by a8m** [comment]
Hey! The issue was fixed in the latest build. Please, upgrade Atlas and report if you still face issues with this.
